appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.shopjoy.ecadminapi.config.P6SpyFormatter
driverlist=org.postgresql.Driver
deregisterdrivers=true
dateformat=HH:mm:ss.SSS
excludecategories=info,debug,result,resultset,commit,rollback,batch
filter=true
exclude=SET,SHOW,BEGIN
